[package]
name = "todoki-protocol"
version = "0.1.0"
edition.workspace = true

[features]
default = []
schematic = ["dep:gotcha"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
gotcha = { workspace = true, optional = true }
